# ------------------------------------------------------------------------------
# Program Name: B1.processing_tas.R
# Authors: Leeya Pressburger
# Date Last Modified: March 2022
# Program Purpose: Processing CMIP6 tas data and calculating Tgav
# Inputs: csv files generated by corresponding .py scripts
# Outputs: One csv file with annual tas values for all CMIP6 
# model/experiment/ensemble runs and annual Tgav values for models with
# historical runs; ggplot visualizations
# TODO:
# ------------------------------------------------------------------------------

# Import packages
library(readr)
library(dplyr)
library(ggplot2)
library(here)

# Set file paths, based on repo
BASE_DIR <- here::here()

path1 <- paste0(BASE_DIR, "/tas/csv1")
path2 <- paste0(BASE_DIR, "/tas/csv2")

# Access files
files1 <- list.files(path = path1, pattern = "*.csv", full.names = TRUE)
files2 <- list.files(path = path2, pattern = "*.csv", full.names = TRUE)

# Read in data, forcing column types
data1 <- lapply(files1, read_csv, col_types = "dccccccdd") %>%
  bind_rows(.id = "File")

data2 <- lapply(files2, read_csv, col_types = "dccccccdd") %>% 
  bind_rows(.id = "File")

# Combine data sets
data <- bind_rows(data1, data2)

# Add name and row number identifier
data$name <- paste0(data$model, "_", data$experiment, "_", data$ensemble)
data$rownum <- seq_len(nrow(data))

# Correct non-conventional years in CO2 forcing experiments
# Scale to start at 1850
years <- data %>%
  select("rownum", "year", "File") %>%
  filter(year < 1850 | year > 2500) %>%
  group_by(File) %>%
  mutate(start_year = year[1],
         scale = year - start_year,
         new_year = 1850 + scale) %>%
  select("rownum", "new_year")

# Combine with original dataframe
tas <- left_join(data, years, by = "rownum")

# Problem - need to make one year column with "year" and "new_year"
# If new_year has an NA, replace it with year, otherwise leave as is
replace_year <- ifelse(is.na(tas$new_year), 
                       tas$year, 
                       tas$new_year)

# Put new year column in data set
tas$year <- replace_year

# Get rid of unnecessary columns
tas <- tas %>% select(c(-new_year, -File.y, -X1))

# Get historical average
histo <- tas %>%
  filter(experiment == "historical") %>%
  group_by(model) %>%
  mutate(hist_av = mean(value))

# Isolate historical models and calculate their averages
historical <- as.data.frame(unique(histo$model))
historical$avg <- unique(histo$hist_av)
colnames(historical) <- c("model", "avg")

# What models have Tgav values
models <- historical$model

# Filter and calculate
Tgav <- tas %>%
  filter(model %in% models) %>%
  left_join(historical, by = "model") %>%
  mutate(Tgav = value - avg)

# Join Tgav to original data set, but only for the rows/models that have historical data
Tgav_out <- Tgav %>% select(rownum, Tgav)

output <- left_join(tas, Tgav_out, by = "rownum")
output$type <- "global"

# Clean up output data
out <- output %>%
  select(c(model, experiment, ensemble, variable, year, value, units, type, Tgav))

out_tgav <- out %>% 
  select(-c(variable, value)) %>%
  pivot_longer(cols = Tgav, names_to = "variable", values_to = "value")
out_tgav$units <- "deg C"

out <- out %>% select(-Tgav)
out <- rbind(out, out_tgav)

# Save outputs to csv
write.csv(out, "./outputs/CMIP6_annual_tas_global.csv", row.names = FALSE)

# Data visualization
# Plot results
plot_t <- output %>% 
  ggplot(aes(year, value, color = model, group = paste(model, experiment, ensemble))) +
  geom_line() +
  facet_wrap(~experiment, scales = "free_x") +
  labs(x = "Year",
       y = "K",
       title = "Global surface temperature") +
  theme_minimal()

# Filter for particular experiments
co2exp <- output %>% filter(experiment %in% c("1pctCO2", "abrupt-2xCO2", "abrupt-4xCO2"))
hist <- output %>% filter(experiment == "historical")
ssps <- output %>% filter(experiment %in% c("ssp119", "ssp126", "ssp245", "ssp370", 
                                          "ssp434", "ssp460", "ssp534-over", "ssp585"))
# Plot just particular experiments
plot_co2 <- co2exp %>%
  ggplot(aes(year, value, color = experiment, group = paste(model, experiment, ensemble))) +
  geom_line() +
  labs(x = "Year",
       y = "K",
       title = "Global surface temperature") +
  facet_wrap(~model) +
  theme_minimal()

plot_hist <- hist %>%
  ggplot(aes(year, value, color = experiment, group = paste(model, experiment, ensemble))) +
  geom_line() +
  labs(x = "Year",
       y = "K",
       title = "Global surface temperature") +
  facet_wrap(~model) +
  theme_minimal()

plot_ssps <- ssps %>%
  ggplot(aes(year, value, color = experiment, group = paste(model, experiment, ensemble))) +
  geom_line() +
  labs(x = "Year",
       y = "K",
       title = "Global surface temperature") +
  facet_wrap(~model) +
  theme_minimal()
