# ------------------------------------------------------------------------------
# Program Name: B1.processing_idealized_tas.R
# Authors: Leeya Pressburger
# Date Last Modified: Feburary 2024
# Program Purpose: Processing CMIP6 tas data and calculating Tgav
# Inputs: csv files generated by corresponding .py scripts
# Outputs: One csv file with annual tas values for all CMIP6 
# model/experiment/ensemble runs and annual Tgav values for models with
# historical runs; ggplot visualizations
# TODO: This should be integrated with the B1.processing_tas.R script
# ------------------------------------------------------------------------------

DATA_DIR <- here::here("tas")
all_cmip_files <- list.files(DATA_DIR, pattern = ".csv", full.names = TRUE, recursive = TRUE)
# Subset for specific experiments 
exps_patterns <- c("1pctCO2|abrupt-4xCO2")
to_process <- all_cmip_files[grepl(pattern = exps_patterns, x = all_cmip_files)]

lapply(to_process, function(f){
  data <- read.csv(f)
  ref_values <- data[which.min(data$year), ]
  data$value <-  data$value - ref_values$value
  data$year <- data$year - ref_values$year
  data <- select(data, variable, model, experiment, year, value, ensemble)
  return(data)
}) %>%  
  bind_rows() -> 
  idealized_rslst

cmip6_ecs <- as.data.frame(rbind(c("ACCESS-CM2", 4.7),
                                 c("ACCESS-ESM1-5", 3.9),
                                 c("CAMS-CSM1-0", 2.3),
                                 c("CanESM5", 5.6),
                                 c("CESM2", 5.2),
                                 c("CESM2-WACCM", 4.8),
                                 c("CMCC-CM2-SR5", 3.52) ,  
                                 c("HadGEM3-GC31-LL", 5.6),
                                 c("MIROC-ES2L", 2.7),
                                 c("MIROC6", 2.6),
                                 c("MRI-ESM2-0", 3.2),
                                 c("NorESM2-MM", 2.5),
                                 c("TaiESM1", 4.31),        
                                 c("UKESM1-0-LL", 5.3), 
                                 c("CMCC-ESM2", 3.57)))
names(cmip6_ecs) <- c("model", "ecs")

idealized_rslst %>% 
  filter(model %in% cmip6_ecs$model) -> 
  idealized_rslst

# Save outputs to csv
write.csv(idealized_rslst, "./outputs/CMIP6_idealized_tas_global.csv", row.names = FALSE)

