# ------------------------------------------------------------------------------
# Program Name: B2.processing_tas_land.R
# Authors: Leeya Pressburger
# Date Last Modified: March 2022
# Program Purpose: Processing CMIP6 tas data and calculating Tgav (over land)
# Inputs: csv files generated by corresponding .py scripts
# Outputs: One csv file with annual tas values (over land) for all CMIP6 
# model/experiment/ensemble runs and annual Tgav values (over land) for models with
# historical runs; ggplot visualizations
# TODO:
# ------------------------------------------------------------------------------

# Import packages
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(here)

# Set directory, read in files
BASE_DIR <- here::here()
path = paste0(BASE_DIR, "/tas_land")

files <- list.files(path = path, pattern = "*.csv", full.names = TRUE)

# Read in data, forcing column types
data <- lapply(files, read_csv, col_types = "dccccccdd") %>%
  bind_rows(.id = "File")

# Add name and row number identifier
data$name <- paste0(data$model, "_", data$experiment, "_", data$ensemble)
data$rownum <- seq_len(nrow(data))

# Correct non-conventional years in CO2 forcing experiments
# Scale to start at 1850
years <- data %>%
  select("rownum", "year", "File") %>%
  filter(year < 1850 | year > 2500) %>%
  group_by(File) %>%
  mutate(start_year = year[1],
         scale = year - start_year,
         new_year = 1850 + scale) %>%
  select("rownum", "new_year")

# Combine with original dataframe
tas <- left_join(data, years, by = "rownum")

# Problem - need to make one year column with "year" and "new_year"
# If new_year has an NA, replace it with year, otherwise leave as is
replace_year <- ifelse(is.na(tas$new_year), 
                       tas$year, 
                       tas$new_year)

# Combine with original dataframe
tas$year <- replace_year

# Get rid of unnecessary columns
tas <- tas %>% select(c(-new_year, -File.y, -`...1`))

# Get historical decadal average from 1850-1860 to use as a reference point
hist <- tas %>%
  filter(experiment == "historical") %>%
  group_by(model, ensemble) %>%
  filter(year %in% 1850:1900) %>%
  mutate(hist_av = mean(value))

# Isolate historical models and calculate their averages
historical <- hist %>% 
  select(model, ensemble, avg = hist_av) %>% 
  distinct()

# Calculate Tgav
# What models have Tgav values
models <- historical$model

# Filter and calculate
Tgav_land <- tas %>%
  filter(model %in% models) %>%
  left_join(historical, by = c("model", "ensemble")) %>%
  mutate(Tgav = value - avg)

# Join Tgav to original data set, but only for the rows/models that have historical data
Tgav_out <- Tgav_land %>% select(c(rownum, Tgav))

output <- left_join(tas, Tgav_out, by = "rownum")
output$type = "land"

# Data visualization
# Graph tas_global vs tas_land - only for models with Tgav values
Tgav_land$type <- "land"

# Combine global and land values
# Access only needed columns
Tgav_l_plot <- Tgav_land %>%
  select(c(year, value, model, experiment, ensemble, type))

# Using global data from "B1.processing_tas.R"
Tgav <- read.csv("./outputs/cmip6_annual_tas_global.csv")
Tgav_plot <- Tgav %>%
  select(year, value, model, experiment, ensemble, type)

plot_data <- bind_rows(Tgav_l_plot, Tgav_plot)

Tgav_models_compare <- plot_data %>%
  # This model has an abnormally low tas_land value
  filter(model != "MPI-ESM1-2-LR") %>%
  ggplot(aes(year, value, color = type, 
             group = paste0(model, experiment, ensemble, type))) +
  geom_line() +
  facet_wrap(~experiment, scales = "free") +
  labs(x = "Year",
       y = "tas",
       title = "CMIP6 runs - tas over time (models with Tgav values)") +
  theme_minimal()

# All models
tas$type = "land"
tas_l_plot <- tas %>%
  select(c(year, value, model, experiment, ensemble, type))

# Using Tgav from "processing_tas.R" (same as above)
tas_plot <- Tgav %>%
  filter(variable == "tas") %>%
  select(year, value, model, experiment, ensemble, type)

plot_all_data <- bind_rows(tas_l_plot, tas_plot)

# Some models have very low tas_land values - identified from plots
low_models <- tas %>% 
  filter(value < 200)
low_models <- unique(low_models$model)

all_models_compare <- plot_all_data %>%
  # These model have abnormally low tas_land values
  filter(!model %in% low_models) %>%
  ggplot(aes(year, value, color = type, 
             group = paste0(model, experiment, ensemble, type))) +
  geom_line() +
  facet_wrap(~experiment, scales = "free") +
  labs(x = "Year",
       y = "K",
       title = "Surface temperature over land") +
  theme_minimal()

# Plot just tas_land models
tas_land_plot <- tas %>%
  filter(!model %in% low_models) %>%
  ggplot(aes(year, value, color = model, 
             group = paste0(model, experiment, ensemble))) +
  geom_line() +
  facet_wrap(~experiment, scales = "free") +
  labs(x = "Year",
       y = "K",
       title = "Surface temperature over land") +
  theme_minimal()

# Clean up output data, save csv
out <- output %>%
  select(c(model, experiment, ensemble, variable, year, value, units, type, Tgav)) %>%
  # Remove outliers
  filter(!model %in% low_models)

out_tgav <- out %>% 
  select(-c(variable, value)) %>%
  pivot_longer(cols = Tgav, names_to = "variable", values_to = "value")
out_tgav$units <- "deg C"

out <- out %>% select(-Tgav)
out <- rbind(out, out_tgav)

write.csv(out, "./outputs/CMIP6_annual_tas_land.csv", row.names = FALSE)
