# ------------------------------------------------------------------------------
# Program Name: B5.processing_rh.R
# Authors: Leeya Pressburger
# Date Last Modified: March 2022
# Program Purpose: Processing CMIP6 rh data
# Inputs: csv files generated by A5.rh.py
# Outputs: One csv file with annual rh values for all CMIP6 
# model/experiment/ensemble runs, ggplot visualizations
# TODO:
# ------------------------------------------------------------------------------

# Import packages
library(readr)
library(dplyr)
library(ggplot2)
library(here)

# Set directory, read in files
BASE_DIR <- here::here()
path = paste0(BASE_DIR, "/rh")

files <- list.files(path = path, pattern = "*.csv", full.names = TRUE)

# Read in data, forcing column types
data <- lapply(files, read_csv, col_types = "dccccccddd") %>%
  bind_rows(.id = "File")

# Add name and row number identifier
data$name <- paste0(data$model, "_", data$experiment, "_", data$ensemble)
data$rownum <- seq_len(nrow(data))

# Correct non-conventional years in CO2 forcing experiments
# Scale to start at 1850
years <- data %>%
  select("rownum", "year", "File") %>%
  filter(year < 1850 | year > 2500) %>%
  group_by(File) %>%
  mutate(start_year = year[1],
         scale = year - start_year,
         new_year = 1850 + scale) %>%
  select("rownum", "new_year")

# Combine with original dataframe
rh <- left_join(data, years, by = "rownum")

# Problem - need to make one year column with "year" and "new_year"
# If new_year has an NA, replace it with year, otherwise leave as is
replace_year <- ifelse(is.na(rh$new_year), 
                       rh$year, 
                       rh$new_year)

# Combine with original dataframe
rh$year <- replace_year

# Get rid of unnecessary columns
rh <- rh %>% select(c(-new_year, -File.y, -X1))

# Unit conversion
# Convert kg/m2/s to Pg/gridcell/year
values <- rh$value * (1e-12) * (3.15e7) * rh$land_area

rh <- rh %>%
  mutate(value = round(values, 4),
         units = "Pg/yr")

# Data visualization
# Remove abnormally low models
rh_low <- filter(rh, value < 10)
low_models <- unique(rh_low$model)
rh <- rh %>% 
  filter(!model %in% low_models)

# Plot rh over time
rh_plot <- ggplot(rh, aes(year, value, color = model, 
               group = paste0(model, experiment, ensemble))) +
  geom_line() +
  facet_wrap(~experiment, scales = "free") +
  labs(x = "Year",
       y = "Pg C",
       title = "Total Heterotrophic Respiration on Land as Carbon Mass Flux") +
  theme_minimal()

# Clean up output data
output <- rh %>%
  select(c(model, experiment, ensemble, variable, year, value, units))

# Save outputs to csv
write.csv(output, "./outputs/CMIP6_annual_rh_land.csv", row.names = FALSE)
